version: '3'

services:
  # 应用服务
  app:
    build: .
    container_name: smartband-app
    restart: always
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGO_URI=mongodb://mongodb:27017/smartband
      - JWT_SECRET=your_jwt_secret_key
    depends_on:
      - mongodb
    volumes:
      - ./:/app
      - /app/node_modules

  # MongoDB服务
  mongodb:
    image: mongo:latest
    container_name: smartband-mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 